### ISSUE TITLE
Public API endpoints

### ISSUE THREAD

**Issue by hexjelly** [elmadev/elmaonline-site#15]
Should plan this at some point as well. Decide on what to add beyond the current available features etc. Let's maybe make it have a version in URL so any possible future implementations would keep things backwards compatible? Probably a non-issue with how limited its use is in our scene and the fact it's doubtful a new version will be made before Elma 2 comes anyway. But either way it would be as easy as just putting "v2" or whatever in URL somewhere so doesn't hurt much.

Put together something consistent with proper fields and error messages. Maybe also consider putting proper referencing to own API at other endpoints (see [http://stateless.co/hal_specification.html](http://stateless.co/hal_specification.html)!)

Didn't use it yet, but I believe mentioned elsewhere as well, probably worth looking into using [GraphQL](http://graphql.org/learn/)?

**Comment by hexjelly** [comment]
https://apiary.io/ etc reminder

**Comment by RobinManoli** [comment]
Some ideas for improving API:

API 3.0

I suggest to make the API a bit more intuitive, consistent and also give it the possibility to have more relevant data, more efficiently. Also, it would be really useful to create the possibility to start a battle or upload a level with the api.

-----------
- UPLOADS
-----------
Upload could be done through an EOL account with supplied password:
https://elma.online/api3.0/upload_level/ribot/mypass + levdata --- returns level id
https://elma.online/api3.0/startbattle?u=ribot&p=mypass&battletype=x&battlelength=10... + levdata --- returns battle id



---------
- TIMES
https://elma.online/api3.0/times/8850-8860
---------
Old output: {
  "1": {
    "number": 1,
    "kuski": "Mpq",
    "kuskiindex": 77,
    "team": "",
    "nation": "se",
    "time": "00:58,13",
    "timeindex": 6375577
  }
}

Questions:
- The parameters are still difficult to understand even with example data. What means bestall and startindex?
- Why are only some functions outputting xml? Is there really a need for xml?

Suggested output:
- List instead of dictionary
- Remove timeformat option and always output both possibilities
- Add level designer and other lev info
- Timeindex should be renamed to be more intuitive (probably related to startindex), perhaps using a timestamp or unixtime if possible
- Should probably rename *index to *id, such as levelid and kuskiid
- Possibility to get data from multiple levels, decided by last argument if it's an integer or a range
- More intuitive parameters names, such as bestonly rather than bestall


{
  "levels": [
    {
      "levelid": 8851,
      "designer": {
        "kuskiid": 78,
        "kuski": "jokke"
      },
      "times": [
        {
          "kuski": "Mpq",
          "kuskiindex": 77,
          "team": "",
          "nation": "se",
          "time_str": "00:58,13",
          "time_float": "58.13",
          "timeindex": 6375577
        },
        {
          "kuski": "jokke",
          "kuskiindex": 78,
          "team": "",
          "nation": "se",
          "time_str": "00:59,13",
          "time_float": 59.13,
          "timeindex": 6375579
        }
      ]
    }
  ]
}



-----------
- BATTLES
https://elma.online/api3.0/battles/12300-12399
-----------
Old output:
{
  "1": {
    "number": 1,
    "kuski": "GraduS",
    "kuskiindex": 185,
    "team": "ZOT",
    "nation": "ru",
    "time": "00:21,08",
    "timeindex": 121156160
  }
}

Suggested output:
- List instead of dictionary
- Remove timeformat option and always output both possibilities
- Possibility to get data from multiple battles, decided by last argument if it's an integer or a range

{
  "battles": [
    {
      "battleid": 10749,
      "results": [
        {
          "number": 1,
          "kuski": "GraduS",
          "kuskiindex": 185,
          "team": "ZOT",
          "nation": "ru",
          "time_str": "00:21,08",
          "time_float": 21.08,
          "timeindex": 121156160
        }
      ]
    }
  ]
}

---------
- KUSKI
https://elma.online/api3.0/kuski/Lousku,jokke,113,...
---------
- Called kuski instead of player/nick for consistency
- Possibility to get data from multiple kuskis, comma separated kuski names or id's

Suggested output:
{
  "kuskis": [
    {
      "kuski": "Lousku",
      "Team": "BAP",
      "Nation": "fi",
      "kuskiid": 111
    }
  ]
}



-------------------
- BATTLE/LEVEL INFO
-------------------
Why not include this with battles/levels above?
What is kuskiindex for a battle?
What is order for a battle?
