### ISSUE TITLE
Decide on frontend framework

### ISSUE THREAD

**Issue by sunehs** [elmadev/elmaonline-site#2]
Leave any comments on frontend frameworks and approaches here.

**Comment by hexjelly** [comment]
I guess it could depend on the backend choice and what plays nice together, or if there is something that takes care of both at the same time. I guess by default I just vote React or Vue because probably can't go too wrong with either choices.

**Comment by demiters** [comment]
I also think the best-supported choices are React and Vue. Next.js is also gaining momentum and while simple to use might not be best suited for the purpose.

I vote React due to personal experience and overwhelming developer community preference.

**Comment by foxtrada** [comment]
React is a bit harder to set up and get into so I would vote for vue. Also I'm not sure if eol site is going to have that kind of features that would make react much preferable, but both oke I guess.

**Comment by demiters** [comment]
1. Read this https://medium.freecodecamp.com/the-5-things-you-need-to-know-to-understand-react-a1dbd5d114a3#.6tjgbejkm
2. Congrats you can write React now

However, I agree Vue is probably easier to get something going if you have no React experience. I haven't used it in real apps though so can't comment other than about what I've read and snippets I've seen. Also Vue seems to have slightly faster rendering times than React lately. Still, React has overall better additional feature package support. In the end I vote for the lead developer to decide imo ;)

**Comment by foxtrada** [comment]
Well, I haven't used either one in real projects so I can't say anything about that, but they are using it for example in Gitlab (here a small article about it [https://about.gitlab.com/2016/10/20/why-we-chose-vue/](url)). Setting up Vue was much more simple process than React, I mean just two weeks ago I was bored and decided to do some more React but the tutorial on their site didn't have any logic and it was jumping and mixing different syntax so I got frustrated and stopped. Anyways, whichever is fine for me, React would be a very good addition to my CV and the userbase is strong so I'm not against it. But I feel like with Vue it might be easier for new people to jump in. After all I think eol site is more about displaying statistics and simple actions rather than being a complicated web app which might benefit more about React components.

**Comment by sunehs** [comment]
react seems easier to learn to me, since it doesn't have as much of its own abstractions, most things are just basic javascript. Getting the structure set up may be complicated, but using some starter kit you can circumvent that, once you have that set up it's pretty easy to understand. Anyway seems there's enough interest in react, so we'll go with that. At least for now, nothing's set in stone yet.

**Comment by hexjelly** [comment]
I think could pretty much coinflip and would be good either way as long as pick something, but yes anyway React sounds good to me at least

**Comment by jgn-epp** [comment]
Sik, then I might just be able to motivate myself to learn a bit of react
