### ISSUE TITLE
Preliminary visual ideas and feedback

### ISSUE THREAD

**Issue by hexjelly** [elmadev/elmaonline-site#24]
While still in planning stage and toying around with different layouts and frameworks, maybe we should post some screenshots or links to stuff here and hear from people what they like or dislike? Can get some general sense of everyone's ideas in one place purely visually, to get a little overview.

**Comment by demiters** [comment]
My mockup for a responsive layout is here: http://codepen.io/artuurs/full/WpaeyZ
Check it out both on desktop and mobile to get a feel for it.
I'll make some more complex views like profile page and home page also.

I do like skint's color scheme and logos obv.

**Comment by hexjelly** [comment]
Mine was just mega quick vomiting out brain ideas for some general look based on that one, no link to anything because it was not made to be useful, and things are not placed accurately etc. Was just to show what had in mind at the time: [screenshot](https://i.imgur.com/r07k9Nv.png)

**Comment by foxtrada** [comment]
This is a quick sketch of a mobile layout, level image on top and some info layered on top of it to save space.
![mobile-layout](https://cloud.githubusercontent.com/assets/11681678/24468255/5bc81090-14c0-11e7-96f2-1cb492a655fc.png)

**Comment by ville-j** [comment]
For a reference I'll post this here too: http://janka.la:5000/#/

Ideas behind this designs were:

- Battles are real-time and they are the cornerstone of the game, so it would make sense to have a real-time feed of the battles on the side. This way, wherever you are on the site, you can easily see what is on and what is in the queue. It will draw more attention to the battles that they deserve, whether you are a new or a returning visitor. If you are on a mobile, it probably isn't needed at all since since you might not potentially be joining the battle at that moment.
- Battles dashboard should have some kind of daily (or perhaps weekly) top stats displayed by default. It could create more competitive atmosphere since these stats vary more. If the "main" stats are yearly stats no one's going to bother to beat someone with 800 won battles, but in daily or weekly stats that's easier.  Also designers' efforts have always been neglected and putting some highlighted stats about them also on the dashboard might be motivating.
