### ISSUE TITLE
Upload replay

### ISSUE THREAD

**Issue by sunehs** [elmadev/elmaonline-site#29]
- Upload form
- Read time data etc.
- Save to replay db table

**Comment by sunehs** [comment]
Some issues left

**Comment by pawq** [comment]
Current issues:
- the "TAS" flag doesn't have any effect
- the "unlisted" flag doesn't have any effect
- uploading a replay with "Driven by" empty results in a broken page
- uploading a replay whose level is not in the database assigns a default "0" value for the level, making the rec appear in the list, but its page shows a blank recplayer. I guess there should be a prompt "can't upload rec without lev" and rec should be rejected.
- the "Latest replays" list doesn't automatically refresh after an upload is made

**Comment by sunehs** [comment]
- [ ] show link to uploaded replay (especially important for unlisted, since you don't know the url otherwise)

**Comment by pawq** [comment]
[ ] Include a "cheated"/"nitro" flag

Arzenik's April Fools replay (ha ha...) made me think about this. Technically, I think "TAS" includes both saveload and any other cheated recs, but I think we should differentiate those. Before you ask "why allow xiit recs in the first place", Nitro has been known to be a fun-for-some tool almost since the beginning of Elma, and some quite well-known recs exist. I think it would be silly to ban them from the rec database, because they're part of the scene and are not going away. Instead, I think it's more fitting to simply have an appropriate flag in the database. I guess "Nitro" is an oke option, since it's broadly understood to mean edited game physics.

**Comment by pawq** [comment]
- [ ] Make the uploaded replay box (with filename and url) disappear at some point (for example when a new replay has been selected for upload)

**Comment by Ben3eeE** [comment]
- [ ] Filters doesn't stay when navigating to a different rec in the same level
![bear](https://user-images.githubusercontent.com/1058982/55653450-df32eb80-57ee-11e9-9072-bdf1bf1f01b0.gif)

**Comment by pawq** [comment]
- [ ] Check if replay has level in database when replay is selected, not when clicking "Upload"

**Comment by pawq** [comment]
- [ ] Implement batch uploading of replays.

One option would be to allow selection of multiple files, and then the possibility to set properties/flags for each individually in a long list (and probably with a "apply to all" option).

Another would be to have some sort of .zip+.csv system, where the zip would contain recs and the csv the properties and flags. But I've got a feeling this is a horrible idea :smile:

Anyway, as the new site is meant to be the ultimate rec database (right?), I think batch uploading is a necessity.

**Comment by sunehs** [comment]
Some of these to own issues so we can close this.

>     * [ ]  Check if replay has level in database when replay is selected, not when clicking "Upload"
This is not possible, or would at least require big rewrite of uploading logic, as all the checking of level is done on server side.

>     * [ ]  (Cosmetic) Left-align all column headers and column contents in the "Latest Replays" table (as it is in the "Latest Battles" table. Replay tags will need to be putted after the time, instead of in front.
I'd argue it's better to have times right aligned so ,000 and always right underneath each other for example. Could accomplish with leading zeroes but don't like that either.

**Comment by pawq** [comment]
> This is not possible, or would at least require big rewrite of uploading logic, as all the checking of level is done on server side.

Would it be possible to try uploading rec to db as soon as it's selected (so that the check is made then) and keep its handle, then update its info with whatever the user inputs below? If it sounds unfeasible or impsy effort then nvm, it's fine as it is I guess.

> I'd argue it's better to have times right aligned so ,000 and always right underneath each other for example. Could accomplish with leading zeroes but don't like that either.

That's a good point with the time alignment. I'll be looking at column width formatting anyway cuz it's kinda all over the place everywhere, could maybe then look to align those somehow nicely while keeping formatting of all tables consistent.

Don't mind closing the issue now 👍
