### ISSUE TITLE
Open source code of backend, frontend or both?

### ISSUE THREAD

**Issue by demiters** [elmadev/elmaonline-site#3]
I think security through obscurity is not a great argument, so having all code public could help spot issues faster. Opinions?

**Comment by hexjelly** [comment]
Realistically, what are the potential "secrets" of backend exactly anyway here? SQL schemas? There is no EOL related code (as in EOL server etc.) anyway involved beyond that.

**Comment by sunehs** [comment]
My thought was having it all open source, since that makes it easier for someone to come in and make some small fix, without having to go through some process of asking for access etc. Releasing SQL schema is arguably a security risk, makes it easier to mess something up if queries aren't safe. We could make some abstraction I guess which is obscured, but if people can't test it themselves with a copy of db it's pretty much impossible to do any backend work. So just need to make sure queries are secure.

**Comment by hexjelly** [comment]
Easily avoided by using prepared statements in SQL for the most part anyway. Will definitely want to have schemas for testing and stuff, maybe populated with some randomly generated data so can test performance of different queries and make sure everything is working too. Easier to find bugs when you are testing pages and layout etc with hundreds of entries instead of just a couple, so you know how pagination and query limits will affect stuff in different places.
