### ISSUE TITLE
Find best approach for showing names in place of Indices

### ISSUE THREAD

**Issue by sunehs** [elmadev/elmaonline-site#32]
If you see the current site, kuski name, level name etc. is just shown as the Index from the battle table. Need to figure out best approach for reading this data.

- DB joins?
- MongoDB?
- Some basic json data?
- Something else?

**Comment by hexjelly** [comment]
Still not had much time to look at everything, but starting to get feel for structure of project. Wouldn't this just be a simple GraphQL query, where you fetch name of kuski/level based on id, and then use this resolver thing in battle query etc? Or did you mean something else that I didn't brain while reading question? 8)

**Comment by ville-j** [comment]
There are now working examples how to get the information both directly in the query and with separate components. Most of the time the direct method ("join") is probably better since the components seem to work async and make separate requests to the server from user's browser.. no idea if you could render it on the server side but anyways it might be useful sometimes since it's very easy to use.

**Comment by sunehs** [comment]
My reason for not using joins is that it adds to the complexity of the sql query. If you need both the Nick, the team, a level name etc. that's already a lot of indices used, and then if you're doing some where's order's etc. in my experience on the old site at some point it just can't use index on everything even if they're there.

Apollo caches the queries on client side, so it only needs to get a nick once for example. Only saves per session though, but it's possible to add some persistant cache as well. Since nicks, level names etc. don't really change, some old cached version should mostly be fine. On server side I looked into redis to cache these queries, but haven't tried it out yet.

Anyway now we have both approaches, we can see how it works out once we get to more complex queries.

**Comment by ville-j** [comment]
It sounds a bit odd that joins would become a problem since that's what relational databases are all about, but yeah that's good to know. Also caching is a good point, this probably isn't a big concern at this stage.

**Comment by TemperGrace** [comment]
MySQL will handle a lot of indices quite fine, from many tables joined together or w/e method used to collect these indices. MySQL is - at its heart - good at pulling data, but not good at organising it. With large datasets and complex queries, adding WHERE and ORDER clauses that have complex interactions will slow down your query drastically. Don't be scared of JOINs. The right JOIN will always be the correct implementation.

I guess the point that I'm making is that often the fastest solution to this problem is to collect all of the data (including relevant WHERE clauses) and sort the array post-query outside of MySQL.
