### ISSUE TITLE
YALE integration

### ISSUE THREAD

**Issue by hexjelly** [elmadev/elmaonline-site#46]
There was already an issue about 3rd party integrations, but figured maybe there should be a specific issue for YALE.

I think it would be a nice addition to the site. Specially if you were able to implement some sort of invitation system or persistent "rooms" where people can collaborate on a level, or multiple. Maybe even make it possible to start battles from the site with these levels? Potentially with some permission flag so there's not random spam from just anyone, and people starting without testing levels etc., if it's needed.

I remember VJ shared code once, maybe he can paste it to some folder or whatever in a branch?

I could maybe take a look at doing the whole websocket integration with it, if it needs any work to get going. Not sure what the errors were that made the original stop working; code or was it just unmaintainable VPS?

**Comment by ville-j** [comment]
I have a complete rewrite of the server, editor and ui on GitLab atm, I will move it to GitHub once I've done some code cleaning. It doesn't require a lot of integration as such, you can just drop the script to any site. The server has to be of course ran somewhere, it's a separate module written in nodejs so that can be "integrated" in the eol site probably if need be, or then ran completely separately.

Why the original YALE stopped working was simply that the server would occasionally crash for whatever reason and would need to be restarted. Eventually I reinstalled the whole vps for newer OS and just didn't care to setup the system again.

**Comment by hexjelly** [comment]
👀 Oh sick. Then nvm all of that. Or well at least it's not big priority for now I guess compared to other things, but good to know that it exists.

Glad to hear you are also doing YDD, gj.

**Comment by ville-j** [comment]
Here are the repositories:
[https://github.com/ville-j/level-editor](https://github.com/ville-j/level-editor)
[https://github.com/ville-j/level-editor-gui](https://github.com/ville-j/level-editor-gui)
[https://github.com/ville-j/level-editor-server](https://github.com/ville-j/level-editor-server)

**Comment by ville-j** [comment]
The editor is now integrated in the dev branch. I will close this issue, all feature requests and bugs should be preferably posted in the [https://github.com/ville-j/level-editor-gui](https://github.com/ville-j/level-editor-gui) repository.
