### ISSUE TITLE
Replay page

### ISSUE THREAD

**Issue by ville-j** [elmadev/elmaonline-site#54]
Reference: [http://www.recsource.tv/r/iwdbjtkces](http://www.recsource.tv/r/iwdbjtkces).

Separate page for viewing a single replay.

- Recplayer
- Replay information
- Suggestions; other same level replays
- Comments ?
- Rating ?

**Comment by sunehs** [comment]
Started work on this.

Another thing it could show is best time in level.

Dunno how important comments and ratings are?

Going for some short ish url like: https://elma.online/r/8wnba6o1hd

**Comment by pawq** [comment]
I think ratings and comments were super useful & valuable on the old recsource.

**Comment by pawq** [comment]
Another couple of things:
- I think rec autoplay would be nice, not sure if planned already.
- I think it's actually good that the replay currently played does not disappear from the "Other replays in level" list (so can see how fast it is relative to others), but it should be highlighted there, probably with a more noticeable colour than the hover grey.

Also, I think there was some talk in discord about default sorting, since unfinished replays would currently appear on top. Perhaps there could be a toggle switch on top of the list to change between "Finished" and "Unfinished" replays? (Provided replays have a "finished" flag, which I don't know.) 

In the far future, I think it would be great if, apart from a TAS flag, we could also display a "EOL-verified" flag next to replays that could be matched to online EOL times. Though again, I don't know if that's possible for technical reasons.

**Comment by sunehs** [comment]
Autoplay feature is there, just a matter of what's preferred.

**Comment by pawq** [comment]
I think having it on makes sense. Not only we're all used to it from recsource.tv and recs.zamppe.com, but why would anyone go to a rec page if not to spy rec ;p and I think the first 0.5-1s or so, which is the time it'll take to focus on recplayer, is rarely important enough, and if it is, then can always rewind.

**Comment by ville-j** [comment]
On the other hand many people requested disabling the autoplay because they open several pages at once in new tabs and go through them one by one. This should probably be a user setting with on/off/auto values where auto would start the play if the tab is active on load.

**Comment by pawq** [comment]
Didn't think of that, good point! In that case I'm definitely fine with it off, but as you said, a user setting would be great :)

**Comment by pawq** [comment]
The timezone of battle start time on the mainpage is GMT+1, but in the individual battle page it's in GMT (in the top-right box). Replay page also shows the time in GMT. (My local is GMT btw.) Thought I'd mention it in case unnoticed :)
