### ISSUE TITLE
Unable to upload internal replays

### ISSUE THREAD

**Issue by pawq** [elmadev/elmaonline-site#86]
"Level not found" error message when trying to upload any internal replay.

Tested with all flags on/off and "Driven by" and "Comment" fields empty and non-empty, result always the same. Tried recs from various internals.

**Comment by sunehs** [comment]
made warm up work, just going to note it here for reference. Need to upload the level to db since the level data doesn't exist currently. Secondly need to edit the CRC reference in the file before uploading to db, since the one you get from a real internal replay and a replay in a QWQUU001 external is not same.
