### ISSUE TITLE
Incorrect result sorting on battle pages

### ISSUE THREAD

**Issue by pawq** [elmadev/elmaonline-site#91]
Results on battle pages are not sorted correctly.

Example: https://elma.online/battles/142113

Rather than by time ascending, it seems that the results are sorted by the time the time was driven at, also ascending (hh:mm:ss timestamp of the kuski's final time). Can see this by looking at the timestamps on elmaonline.net (https://elmaonline.net/statistics/level/429988).

The winners on https://elma.online/battles seem to be correct though.

**Comment by pawq** [comment]
Time results on their own are sorted correctly now, as are apple results on their own, but results with a mix of apple and time results are still messed up (can't figure out a pattern). Examples:
https://elma.online/battles/142141
https://elma.online/battles/142139
https://elma.online/battles/142138
https://elma.online/battles/142137

Also, it seems that results with the same number of apples (ties) are sometimes displayed in a different order than at elmaonline.net, though I have no idea which may be correct, I remember there were some issues with that on the old site too. Example:
https://elma.online/battles/142143
https://elmaonline.net/battles/142143

**Comment by ville-j** [comment]
Ah that's right there is a condition missing that wasn't caught since the test db seems to give the results in correct order in the first place but the live db doesn't. If the apple count or time is exactly the same then the one that has a lower index number in the db (which basically should indicate it was driven and inserted into db first) is sorted first which should work.

**Comment by pawq** [comment]
So it still needs a fix, do I get it right? And any idea about the first issue?

**Comment by ville-j** [comment]
Yes my post was actually trying to cover both issues.. so a fix is coming for the first problem (apple results mixed with time results), and the second thing you mentioned (times or apple results equal) should already work correctly.

**Comment by sunehs** [comment]
For something like battle 142143 it's actually wrong on both sites :D
It's an apple battle, which means it doesn't have TimeIndex (the result isn't a specific run), so they're all 0 and ordering will be whatever. We can however sort by BattleTimeIndex instead.

Fixed in https://github.com/elmadev/elmaonline-site/commit/9bebde010283b79d39865f8269eb6c1aa6c76f8f

**Comment by pawq** [comment]
Can you please explain what info BattleTimeIndex contains?
